/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyresRouteImport } from './routes/tyres'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealersRouteImport } from './routes/dealers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AlloysRouteImport } from './routes/alloys'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceIdRouteImport } from './routes/service.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as DealerIdRouteImport } from './routes/dealer.$id'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated.vendor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated.vendor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated.account.index'
import { Route as AuthenticatedVendorServicesRouteImport } from './routes/_authenticated.vendor.services'
import { Route as AuthenticatedVendorRegisterRouteImport } from './routes/_authenticated.vendor.register'
import { Route as AuthenticatedVendorProfileRouteImport } from './routes/_authenticated.vendor.profile'
import { Route as AuthenticatedVendorProductsRouteImport } from './routes/_authenticated.vendor.products'
import { Route as AuthenticatedVendorMembershipRouteImport } from './routes/_authenticated.vendor.membership'
import { Route as AuthenticatedVendorEnquiriesRouteImport } from './routes/_authenticated.vendor.enquiries'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated.admin.vendors'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated.admin.reports'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated.admin.products'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated.admin.enquiries'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated.admin.cms'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated.admin.catalog'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated.admin.banners'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated.account.profile'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated.account.notifications'
import { Route as AuthenticatedAccountFavouritesRouteImport } from './routes/_authenticated.account.favourites'
import { Route as AuthenticatedAccountEnquiriesRouteImport } from './routes/_authenticated.account.enquiries'
import { Route as AuthenticatedAccountDealersRouteImport } from './routes/_authenticated.account.dealers'

const TyresRoute = TyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersRoute = DealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AlloysRoute = AlloysRouteImport.update({
  id: '/alloys',
  path: '/alloys',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerIdRoute = DealerIdRouteImport.update({
  id: '/dealer/$id',
  path: '/dealer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedVendorServicesRoute =
  AuthenticatedVendorServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorRegisterRoute =
  AuthenticatedVendorRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorProfileRoute =
  AuthenticatedVendorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorProductsRoute =
  AuthenticatedVendorProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorMembershipRoute =
  AuthenticatedVendorMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorEnquiriesRoute =
  AuthenticatedVendorEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountFavouritesRoute =
  AuthenticatedAccountFavouritesRouteImport.update({
    id: '/favourites',
    path: '/favourites',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountEnquiriesRoute =
  AuthenticatedAccountEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountDealersRoute =
  AuthenticatedAccountDealersRouteImport.update({
    id: '/dealers',
    path: '/dealers',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alloys': typeof AlloysRoute
  '/contact': typeof ContactRoute
  '/dealers': typeof DealersRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/tyres': typeof TyresRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/dealer/$id': typeof DealerIdRoute
  '/product/$id': typeof ProductIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/account/dealers': typeof AuthenticatedAccountDealersRoute
  '/account/enquiries': typeof AuthenticatedAccountEnquiriesRoute
  '/account/favourites': typeof AuthenticatedAccountFavouritesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/vendor/enquiries': typeof AuthenticatedVendorEnquiriesRoute
  '/vendor/membership': typeof AuthenticatedVendorMembershipRoute
  '/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/register': typeof AuthenticatedVendorRegisterRoute
  '/vendor/services': typeof AuthenticatedVendorServicesRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alloys': typeof AlloysRoute
  '/contact': typeof ContactRoute
  '/dealers': typeof DealersRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/tyres': typeof TyresRoute
  '/dealer/$id': typeof DealerIdRoute
  '/product/$id': typeof ProductIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/account/dealers': typeof AuthenticatedAccountDealersRoute
  '/account/enquiries': typeof AuthenticatedAccountEnquiriesRoute
  '/account/favourites': typeof AuthenticatedAccountFavouritesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/vendor/enquiries': typeof AuthenticatedVendorEnquiriesRoute
  '/vendor/membership': typeof AuthenticatedVendorMembershipRoute
  '/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/register': typeof AuthenticatedVendorRegisterRoute
  '/vendor/services': typeof AuthenticatedVendorServicesRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/alloys': typeof AlloysRoute
  '/contact': typeof ContactRoute
  '/dealers': typeof DealersRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/tyres': typeof TyresRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/dealer/$id': typeof DealerIdRoute
  '/product/$id': typeof ProductIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/_authenticated/account/dealers': typeof AuthenticatedAccountDealersRoute
  '/_authenticated/account/enquiries': typeof AuthenticatedAccountEnquiriesRoute
  '/_authenticated/account/favourites': typeof AuthenticatedAccountFavouritesRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/vendor/enquiries': typeof AuthenticatedVendorEnquiriesRoute
  '/_authenticated/vendor/membership': typeof AuthenticatedVendorMembershipRoute
  '/_authenticated/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/_authenticated/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/_authenticated/vendor/register': typeof AuthenticatedVendorRegisterRoute
  '/_authenticated/vendor/services': typeof AuthenticatedVendorServicesRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alloys'
    | '/contact'
    | '/dealers'
    | '/login'
    | '/membership'
    | '/services'
    | '/tyres'
    | '/account'
    | '/admin'
    | '/vendor'
    | '/dealer/$id'
    | '/product/$id'
    | '/service/$id'
    | '/account/dealers'
    | '/account/enquiries'
    | '/account/favourites'
    | '/account/notifications'
    | '/account/profile'
    | '/admin/banners'
    | '/admin/catalog'
    | '/admin/cms'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vendors'
    | '/vendor/enquiries'
    | '/vendor/membership'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/register'
    | '/vendor/services'
    | '/account/'
    | '/admin/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alloys'
    | '/contact'
    | '/dealers'
    | '/login'
    | '/membership'
    | '/services'
    | '/tyres'
    | '/dealer/$id'
    | '/product/$id'
    | '/service/$id'
    | '/account/dealers'
    | '/account/enquiries'
    | '/account/favourites'
    | '/account/notifications'
    | '/account/profile'
    | '/admin/banners'
    | '/admin/catalog'
    | '/admin/cms'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vendors'
    | '/vendor/enquiries'
    | '/vendor/membership'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/register'
    | '/vendor/services'
    | '/account'
    | '/admin'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/alloys'
    | '/contact'
    | '/dealers'
    | '/login'
    | '/membership'
    | '/services'
    | '/tyres'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/vendor'
    | '/dealer/$id'
    | '/product/$id'
    | '/service/$id'
    | '/_authenticated/account/dealers'
    | '/_authenticated/account/enquiries'
    | '/_authenticated/account/favourites'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/profile'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/vendor/enquiries'
    | '/_authenticated/vendor/membership'
    | '/_authenticated/vendor/products'
    | '/_authenticated/vendor/profile'
    | '/_authenticated/vendor/register'
    | '/_authenticated/vendor/services'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlloysRoute: typeof AlloysRoute
  ContactRoute: typeof ContactRoute
  DealersRoute: typeof DealersRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  ServicesRoute: typeof ServicesRoute
  TyresRoute: typeof TyresRoute
  DealerIdRoute: typeof DealerIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ServiceIdRoute: typeof ServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyres': {
      id: '/tyres'
      path: '/tyres'
      fullPath: '/tyres'
      preLoaderRoute: typeof TyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers': {
      id: '/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof DealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alloys': {
      id: '/alloys'
      path: '/alloys'
      fullPath: '/alloys'
      preLoaderRoute: typeof AlloysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$id': {
      id: '/service/$id'
      path: '/service/$id'
      fullPath: '/service/$id'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/$id': {
      id: '/dealer/$id'
      path: '/dealer/$id'
      fullPath: '/dealer/$id'
      preLoaderRoute: typeof DealerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/vendor/services': {
      id: '/_authenticated/vendor/services'
      path: '/services'
      fullPath: '/vendor/services'
      preLoaderRoute: typeof AuthenticatedVendorServicesRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/register': {
      id: '/_authenticated/vendor/register'
      path: '/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof AuthenticatedVendorRegisterRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/profile': {
      id: '/_authenticated/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof AuthenticatedVendorProfileRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/products': {
      id: '/_authenticated/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof AuthenticatedVendorProductsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/membership': {
      id: '/_authenticated/vendor/membership'
      path: '/membership'
      fullPath: '/vendor/membership'
      preLoaderRoute: typeof AuthenticatedVendorMembershipRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/enquiries': {
      id: '/_authenticated/vendor/enquiries'
      path: '/enquiries'
      fullPath: '/vendor/enquiries'
      preLoaderRoute: typeof AuthenticatedVendorEnquiriesRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/favourites': {
      id: '/_authenticated/account/favourites'
      path: '/favourites'
      fullPath: '/account/favourites'
      preLoaderRoute: typeof AuthenticatedAccountFavouritesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/enquiries': {
      id: '/_authenticated/account/enquiries'
      path: '/enquiries'
      fullPath: '/account/enquiries'
      preLoaderRoute: typeof AuthenticatedAccountEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/dealers': {
      id: '/_authenticated/account/dealers'
      path: '/dealers'
      fullPath: '/account/dealers'
      preLoaderRoute: typeof AuthenticatedAccountDealersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountDealersRoute: typeof AuthenticatedAccountDealersRoute
  AuthenticatedAccountEnquiriesRoute: typeof AuthenticatedAccountEnquiriesRoute
  AuthenticatedAccountFavouritesRoute: typeof AuthenticatedAccountFavouritesRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountDealersRoute: AuthenticatedAccountDealersRoute,
  AuthenticatedAccountEnquiriesRoute: AuthenticatedAccountEnquiriesRoute,
  AuthenticatedAccountFavouritesRoute: AuthenticatedAccountFavouritesRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendorRouteChildren {
  AuthenticatedVendorEnquiriesRoute: typeof AuthenticatedVendorEnquiriesRoute
  AuthenticatedVendorMembershipRoute: typeof AuthenticatedVendorMembershipRoute
  AuthenticatedVendorProductsRoute: typeof AuthenticatedVendorProductsRoute
  AuthenticatedVendorProfileRoute: typeof AuthenticatedVendorProfileRoute
  AuthenticatedVendorRegisterRoute: typeof AuthenticatedVendorRegisterRoute
  AuthenticatedVendorServicesRoute: typeof AuthenticatedVendorServicesRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
}

const AuthenticatedVendorRouteChildren: AuthenticatedVendorRouteChildren = {
  AuthenticatedVendorEnquiriesRoute: AuthenticatedVendorEnquiriesRoute,
  AuthenticatedVendorMembershipRoute: AuthenticatedVendorMembershipRoute,
  AuthenticatedVendorProductsRoute: AuthenticatedVendorProductsRoute,
  AuthenticatedVendorProfileRoute: AuthenticatedVendorProfileRoute,
  AuthenticatedVendorRegisterRoute: AuthenticatedVendorRegisterRoute,
  AuthenticatedVendorServicesRoute: AuthenticatedVendorServicesRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
}

const AuthenticatedVendorRouteWithChildren =
  AuthenticatedVendorRoute._addFileChildren(AuthenticatedVendorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedVendorRoute: AuthenticatedVendorRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AlloysRoute: AlloysRoute,
  ContactRoute: ContactRoute,
  DealersRoute: DealersRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  ServicesRoute: ServicesRoute,
  TyresRoute: TyresRoute,
  DealerIdRoute: DealerIdRoute,
  ProductIdRoute: ProductIdRoute,
  ServiceIdRoute: ServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
